---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "helloworld"
spec:
  type: "LoadBalancer"
  selector:
    name: "helloworld"
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
      protocol: "TCP"
